const qs=new URLSearchParams(location.search);
function detectOrigin(){if(qs.get('gclid')||qs.get('gbraid')||qs.get('wbraid')||qs.get('utm_source')==='google')return 'Google Ads';if(['instagram','facebook','meta'].includes((qs.get('utm_source')||'').toLowerCase()))return 'Meta / Instagram';if(document.referrer.includes('google.'))return 'Google orgânico';if(document.referrer)return 'Referência';return 'Acesso direto';}
const origemLead=document.querySelector('#origemLead');if(origemLead)origemLead.value=detectOrigin();const campanhaLead=document.querySelector('#campanhaLead');if(campanhaLead)campanhaLead.value=qs.get('utm_campaign')||'';const paginaEntrada=document.querySelector('#paginaEntrada');if(paginaEntrada)paginaEntrada.value=location.pathname||'/';
const money=s=>{if(!s)return NaN;let v=s.replace(/[^0-9,.-]/g,'').replace(/\./g,'').replace(',','.');return parseFloat(v)};
document.querySelector('#calcBtn').onclick=()=>{let a=money(old.value),b=money(now.value),r=document.querySelector('#result');if(a>0&&b>=0){let p=((b/a)-1)*100;r.querySelector('strong').textContent=(p>=0?'+':'')+p.toFixed(2).replace('.',',')+'%';r.querySelector('span').textContent=`De R$ ${a.toFixed(2).replace('.',',')} para R$ ${b.toFixed(2).replace('.',',')}.`;}else{r.querySelector('strong').textContent='—';r.querySelector('span').textContent='Informe valores válidos.'}};
let step=1;
function adaptStep2(){const chosen=document.querySelector('[name=problema]:checked')?.value;document.querySelector('#planFields').style.display=chosen==='SUS'?'none':'block';document.querySelector('#susFields').style.display=chosen==='SUS'?'block':'none';}
function show(n){step=n;if(n===2)adaptStep2();document.querySelectorAll('.pane').forEach(x=>x.classList.toggle('active',+x.dataset.step===n));document.querySelectorAll('.steps i').forEach((x,i)=>x.classList.toggle('active',i<n))}
document.querySelectorAll('.next').forEach(b=>b.onclick=()=>{if(step===1&&!document.querySelector('[name=problema]:checked'))return alert('Selecione o principal problema.');show(Math.min(3,step+1))});
document.querySelectorAll('.back').forEach(b=>b.onclick=()=>show(Math.max(1,step-1)));
document.querySelectorAll('.issue').forEach(b=>b.onclick=()=>{let map={reajuste:'Reajuste elevado',idade:'Faixa etária',coletivo:'Plano coletivo',negativa:'Negativa de cobertura',cancelamento:'Cancelamento',sus:'SUS'},el=[...document.querySelectorAll('[name=problema]')].find(x=>x.value===map[b.dataset.issue]);if(el)el.checked=true;document.querySelector('#analise').scrollIntoView({behavior:'smooth'})});
document.querySelectorAll('.sus-start').forEach(b=>b.onclick=()=>{const el=[...document.querySelectorAll('[name=problema]')].find(x=>x.value==='SUS');if(el)el.checked=true});
document.querySelector('#leadForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);const problema=f.get('problema')||'Direito da Saúde';const origem=f.get('origem')||detectOrigin();const nome=f.get('nome')||'';const msg=`Olá! Acessei o site Saúde em Direito e concluí a triagem.\n\nNome: ${nome}\nAssunto: ${problema}\nOrigem: ${origem}\nGostaria de continuar o atendimento com a equipe.`;const link='https://wa.me/5577998183137?text='+encodeURIComponent(msg);const a=document.querySelector('#successWhatsapp');if(a)a.href=link;document.querySelector('#leadForm').style.display='none';document.querySelector('.steps').style.display='none';document.querySelector('#success').style.display='block'};
